# Generated by Django 3.0.3 on 2020-02-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('classes', models.CharField(max_length=10)),
                ('s_id', models.IntegerField()),
            ],
        ),
    ]
